# Welcome to Jekyll!
#

# Site settings
title: Banner Grinds
description: |
    Junior and Leaving Certificate
    Maths Grinds Online and in Clare
owner: Cian Conway / Daragh McCoy # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: cian.conway@outlook.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Banner-Grinds.github.io" # the base hostname & protocol for your site
social:
    # twitter: https://twitter.com/<username>
    # github: https://github.com/<username>
    linkedin-square: https://linkedin.com/in/cianconway
    facebook-official: https://facebook.com/BannerGrinds
    # google-plus-square: https://plus.google.com/u/0/+<username>
    email: contact@bannergrinds.com
    #flickr:
    #instagram:
    #youtube-square:
    #spotify:
    #stack-overflow:
    #vimeo:
    #reddit:
    #stubleupon:
    #delicious:
    #pied-piper:
    #digg:
    #soundcloud:
    #deviantart:
    #angellist:
    #tumblr-square:
    #stackexchange:
    #weibo:
    #trello:
    #foursquare:
    #linux:
    #bitbucket-square:
    #vk:
    #slack:
    #vine:
    #weixin:
    #yelp:
    #skyatlas:
    #leanpub:
    #connectdevelop:
    #ils:
    #forumbee:
    #tripadvisor:
    #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
